### ISSUE TITLE
KeePass 2 file attachments import

### ISSUE THREAD

**Issue by bits01** [agilebits/onepassword-utilities#11]
Trying to use the converter from KeePass 2 and there are some entries in KP that have file attachments (KP allows them). They don't seem to make it in any form into 1Password, even though attachments seem to be supported in 1P.

**Comment by mikecappella** [comment]
btis01,

Please post your question / request on the AgileBits form, in this thead:

https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

and I will follow-up there.

**Comment by mikecappella** [comment]
This issue is now closed.  It was resolved by supporting KeePass 2 attachment decoding and file creation.  Discussion at the thread above.
