### ISSUE TITLE
Invalid token on converting KeePass2 database

### ISSUE THREAD

**Issue by lukas-schulze** [AgileBits/onepassword-utilities#14]
I tried to convert my KeePass2 database.
However, the converter fails with the following error message:

	perl5.16 convert_to_1p4.pl keepass2 -v my-keepass-database.kdbx 
	Uncaught exception from user code:
		
		not well-formed (invalid token) at line 1, column 0, byte 0:
		Ù¢gûKµ1Áòæ¿qCP¾X!jüZÿ 9ÍÚé#éß_Î0²Áî(®qÛªó¨8GplÝ21p ±z34yp#>¨Üò1#Ì¿KJ©iúU/Jpw \2àÇ0tÈ©£ ¸ÌÌÓðT¼þ!#!!ôpL~»/y	 HhYÌwò[+Æ«ß%píC)Q!%üü	Cû´
		^
		
		
		 at /System/Library/Perl/Extras/5.16/darwin-thread-multi-2level/XML/Parser.pm line 187.
		XML::Parser::parsefile('XML::Parser=HASH(0x7fc8ca0b1818)', 'my-keepass-database.kdbx') called at /System/Library/Perl/Extras/5.16/XML/XPath/XMLParser.pm line 71
		XML::XPath::XMLParser::parse('XML::XPath::XMLParser=HASH(0x7fc8ca0fd410)') called at /System/Library/Perl/Extras/5.16/XML/XPath.pm line 77
		XML::XPath::find('XML::XPath=HASH(0x7fc8cb22d7f8)', '/KeePassFile/Meta/Binaries/Binary', undef) called at /System/Library/Perl/Extras/5.16/XML/XPath.pm line 102
		XML::XPath::findnodes('XML::XPath=HASH(0x7fc8cb22d7f8)', '/KeePassFile/Meta/Binaries/Binary') called at Converters/Keepass2.pm line 66
		Converters::Keepass2::do_import('my-keepass-database.kdbx', undef) called at convert_to_1p4.pl line 116

<img width="1179" alt="screenshot 2015-10-29 10 34 47" src="https://cloud.githubusercontent.com/assets/820580/10814858/c08dc7a2-7e28-11e5-9444-a78b25d3984a.png">

I also could not find a string in my KeePass database containing some parts of this token.

I used KeePass 2.26 on my Windows computer.

**Comment by mikecappella** [comment]
Hi Lukas,

It appears you have exported a KDBX file, and not a Keepass 2 XML file.  Export an XML file, and the converter can read that.

Please ask any additional questions here:

https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

**Comment by lukas-schulze** [comment]
However, exporting KeePass2 as XML does not solve references used in KeePass2.

Is there a way to export solving the references? Could not find oen :-(

**Comment by lukas-schulze** [comment]
I wrote a converted in python to solve references of an XML export of a KeePass2 database.
Can be found here: https://github.com/lukas-schulze/keepass2xml-solve-references

**Comment by mikecappella** [comment]
Sorry, I'd asked that you follow-up via the Converter thread (link posted above).  This isn't the place for discussion of the converter (since I don't manage this site, and others generally won't find it).

The converter also doesn't handle local placeholder tokens.  In my opinion, both of these probably should be supported as part of the Keepass 2 export to XML (with a Resolve Placeholder and REFs option).

That said, it probably isn't too much work to add these to the converter (nobody has asked in the past).
