### ISSUE TITLE
error while trying to set up converter

### ISSUE THREAD

**Issue by femaven** [agilebits/onepassword-utilities#15]
I'm getting the following error using x64 portable Perl using the version of included in the readme.

\onepassword-utilities-master\onepassword-utilities-master\convert_to_1p4>perl convert_to_1p4.pl --help
Bareword found where operator expected at convert_to_1p4.pl line 5, near ""en" class"
        (Missing operator before class?)
Bareword found where operator expected at convert_to_1p4.pl line 13, near "<title>onepassword"
        (Missing operator before onepassword?)
Can't modify numeric lt (<) in scalar assignment at convert_to_1p4.pl line 5, near ""en" class"
syntax error at convert_to_1p4.pl line 5, near ""en" class"
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 62 at convert_to_1p4.pl line 13.
# Module versions & Status

onepassword-utilities-master\onepassword-utilities-master\convert_to_1p4>cpan Date::Calc
CPAN: CPAN::SQLite loaded ok (v0.202)
Database was generated on Thu, 19 Nov 2015 17:39:58 GMT
CPAN: Module::CoreList loaded ok (v2.83)
Date::Calc is up to date (6.4).

onepassword-utilities-master\onepassword-utilities-master\convert_to_1p4>cpan Text::CSV
CPAN: CPAN::SQLite loaded ok (v0.202)
Database was generated on Thu, 19 Nov 2015 17:39:58 GMT
CPAN: Module::CoreList loaded ok (v2.83)
Text::CSV is up to date (1.33).

onepassword-utilities-master\onepassword-utilities-master\convert_to_1p4>cpan XML::XPath
CPAN: CPAN::SQLite loaded ok (v0.202)
Database was generated on Thu, 19 Nov 2015 17:39:58 GMT
CPAN: Module::CoreList loaded ok (v2.83)
XML::XPath is up to date (1.13).

**Comment by mikecappella** [comment]
Hi femaven,

Please post your question/issue on the AgileBits forums in the following thread:

https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1
