### ISSUE TITLE
Import from KeePassX 2 not supported

### ISSUE THREAD

**Issue by ChristianSiegert** [agilebits/onepassword-utilities#16]
1Password Converter does not offer an option to convert CSV files exported from KeePassX 2. The existing KeePassX converter fails to read the exported file as it expects an XML file – KeePassX 2 can only export to CSV. Furthermore, the generic CSV converter cannot handle the KeePassX 2 CSV file because the columns are in a different order.

KeePassX 2 CSV files have the following structure:

```
"Group","Title","Username","Password","URL","Notes"
```

Please add an option to convert KeePassX 2 CSV files.

**Comment by mikecappella** [comment]
@ChristianSiegert ,

See my last comment in this thread:

https://discussions.agilebits.com/discussion/comment/176920/#Comment_176920

Please create a new post on the AgileBits forum if you want to discuss this further, as this is not the right venue for such discussion.
