### ISSUE TITLE
Help: SPB Wallet for Mac Desktop Conversion

### ISSUE THREAD

**Issue by MsMcIntosh** [agilebits/onepassword-utilities#18]
Hi guys, a mid level understanding of everything here. 
can someone help me convert SPB Wallet desktop .swl file? 

followed the step. I see, and think I understand, that person who built utilities didn't write one for a Mac conversation (only windows). 

is there another way to do this? 
I have over 300 passwords - 8yrs accumulated. 

thank you so much.

**Comment by LeohtWT** [comment]
(why was this closed. I received no contact...) Still need help. Thank you.

**Comment by mikecappella** [comment]
Hi LeohtWT,

I wondered the same thing - you opened it, and then **you** immediately closed it!  I figured you found your own answer.

At any rate, please post your questions / comments here:

https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

Github isn't the right place for converters discussions.
