### ISSUE TITLE
Doesn't convert Keychain Items.

### ISSUE THREAD

**Issue by pmtremblay** [agilebits/onepassword-utilities#19]
Bonjour,

I have major issues converting OSX Keychain items.

skip:convert_to_1p4 ptremblay$ cd '/Users/ptremblay/Desktop/onepassword-utilities-master/convert_to_1p4/' && /usr/bin/perl5.16 convert_to_1p4.pl keychain '/Users/ptremblay/Desktop/pm_export.txt' -v
Examined 824 items
Skipped 406 non-login items
Skipped 6 duplicate items
Imported 412 items
Exported 8 note items
Exported 404 login items
Exported 412 total items
You may now import the file /Users/ptremblay/Desktop/1P_import.1pif into 1Password
skip:convert_to_1p4 ptremblay$ 

So, about half of my keychain entries can't be exported correctly. How should I proceed now?

Thanks.
PM

**Comment by mikecappella** [comment]
Hi @pmtremblay,

Please post your issue here:

 https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

as this is not the best place to resolve it.
