### ISSUE TITLE
Error while converting keepass2 file

### ISSUE THREAD

**Issue by jornhenkes** [AgileBits/onepassword-utilities#20]
Hi, 
I'm trying to convert my Keepass2 passwords to 1password, with this converter. I've followed all the steps and tried the different options, but I'm getting this same error every time: 

```
Failed to inflate compressed data: 
Use of uninitialized value $outfile in open at Utils/PIF.pm line 697 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.
    
    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    anid the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.
    
Use of uninitialized value $outfile in concatenation (.) or string at
	Utils/PIF.pm line 697 (#1)
Cannot create 1pif output file: 
No such file or directory
```

I'm using MacOSX for converting the passwords, but I exported my Keepass2 file on a Windows pc. 

Any idea what might go wrong?

**Comment by mikecappella** [comment]
Hi @jornhenkes ,

Please report the issue here:

    https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

and I'll follow-up.

**Comment by radazzouz** [comment]
Thanks for the assist @mikecappella 👍 

@jornhenkes have you tried importing to 1Password using the built-in importer from the main menu (**File > Import...**).

![](https://www.evernote.com/l/AVSv5nQRqhBISb5d_MvYLlehdyclufWbkc0B/image.png)

Please let us know if this helps.

Cheers!

**Comment by jornhenkes** [comment]
Hi @radazzouz and @mikecappella , thanks for the replies and tips. I tried importing a CSV, but then I have to manually set all my folders again, that's quite some work for 800 passwords. So it would be awesome if the importer tool works!

I will see if I can generate a file that shows the issue. I'm afraid it is a specific problem with an entyr, since the same procedure worked fine on another database.

**Comment by mikecappella** [comment]
@jornhenkes .,

I've been awaiting your follow-up in the thread I posted above.   I don't want to have discussions on Github, because others looking for answers in the future typically won't find them here, and keeping things in one location is better for everyone.  Forget CSV for Keepass2, you'll want XML exportsl

**Comment by jornhenkes** [comment]
@mikecappella Super, will post a thread there!
