### ISSUE TITLE
Handle Dashlane files.

### ISSUE THREAD

**Issue by dnlgmzddr** [agilebits/onepassword-utilities#21]
Currently there no easy way to import Dashlane items even the CSV files are a mess in dashlane.

Would be extremely handy to have this automated.

**Comment by mikecappella** [comment]
As you've noticed, Dashlane has problems with its CSV export that makes autmation impossible.  I noted some of the issues here:

https://discussions.agilebits.com/discussion/comment/139608/#Comment_139608

One user list some steps to help cleanup the CSV:

https://discussions.agilebits.com/discussion/comment/317968/#Comment_317968
