### ISSUE TITLE
Update bundle to version 1.0.9 to increase compatibility with Roboform data

### ISSUE THREAD

**Issue by AlexHoffmann** [agilebits/onepassword-utilities#22]
If the RoboForm data contains a number of items with the same name, v1.0.8 of the utilities can fail to convert the data.

MrC already has version 1.0.9 available that fixes this and converts the data well.

Side note:
It converted RoboForm 1714 login items on a HDD machine with 2 GB of RAM in six seconds.

**Comment by AlexHoffmann** [comment]
This is the release I've used for converting RoboForm data: https://www.dropbox.com/sh/g8ruqcmnyafblf6/AAB1WJDRXN-fotmCH0haYn4la/convert_to_1p4_1.09.zip

**Comment by robyoder** [comment]
@mikecappella do you have version 1.09 to PR?
