### ISSUE TITLE
Importing text file from newest version of Keeper Desktop does not work

### ISSUE THREAD

**Issue by crownsedge** [agilebits/onepassword-utilities#27]
Hi,

My mom is coming to 1password from Keeper Desktop version 11.0.0 on macOS. She has a newer version than was listed in the conversion utilities, but I still thought it would likely work. Unfortunately one of the things listed in the instructions, "Export to Excel", was not listed within the "Backup" section of the app -- our only choices were to export to PDF or to a text file (which appears to be some sort of CSV format without a header). I was able to export a text file, which was unable to be read by either the utilities or the CSV importer built into 1password.

If anyone could give some advice on the best way to export data from this app at this point, that would be wonderful. Thank you!

**Comment by mikecappella** [comment]
Howdy.

This isn't a good place for this type of help - can you post your question here:

https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

and I'll follow-up?
Thanks,
MrC

**Comment by crownsedge** [comment]
Sure thing -- my apologies!
