### ISSUE TITLE
$status mismatch in Keepass2 Converter

### ISSUE THREAD

**Issue by resech** [agilebits/onepassword-utilities#29]
I've got a workaround but this might still be something worth reviewing.

When converting an exported Keepass2 XML file, the attachments weren't being written out and I was getting a Failed to inflate compressed data message for each attachment. After a little digging, I found that modifying the status check to the following ('stream end' being the addition) resolved the issue:

`if ($status eq Z_OK or $status eq Z_STREAM_END or $status eq 'stream end') {`

Digging through the zlib documentation it seems like 'stream end' and Z_STREAM_END should be the same thing, so I'm not entirely sure what's going on.

**Comment by mikecappella** [comment]
Following-up here - issue resolved.

i was using the wrong comparison operator (string vs. numeric).  Fix is included in 1.10 version.

Thanks Ross.

**Comment by resech** [comment]
Tested and confirmed.
