### ISSUE TITLE
Where is the development branch ?

### ISSUE THREAD

**Issue by fbonzon** [agilebits/onepassword-utilities#30]
@mikecappella I've downloaded the "Testing Bits" on the forum, contributed some improvements, and want to integrate them here.

But I don't see that new code here. Neither on your fork. How to proceed ? Can you create a branch on your fork with the Testing Bits ?

I'm fixing bugs in the new Yojimbo converter.

**Comment by mikecappella** [comment]
This is not the source code repository for my code, just code I submit to Agilebits.  You can send the code directly to me. My email is at the top of the converter scripts.

**Comment by fbonzon** [comment]
All right. Will send e-mail.

**Comment by robyoder** [comment]
@mikecappella if others are interested in collaborating on these tools, it would make sense to do that here since GitHub was designed for such use, rather than email. :)

**Comment by mikecappella** [comment]
Git was designed for collaboration, yes, but I'm not using it, so simple patches are fine.  A patch against the code I post in "Testing Bits" (my latest) posted here on GitHub to your older code makes little sense, since the patches will not apply cleanly.  Your repository of the code is necessarily out of date almost immediately after you update it.

**Comment by robyoder** [comment]
Yeah. I guess I'm saying it would be nice to encourage community involvement by keeping your repository and our official repository both on GitHub so that the path for making updates is more open and accessible.

**Comment by mikecappella** [comment]
In the 3.5 years I've been doing this, there have been about as many contributions.  :-)

Git on my end is just unnecessary overhead.

What I ultimately check into Git for you is not entirely the same source I work with routinely - some of it goes through transformations, and Git will require me to also manage and submit these tools and my process.
