### ISSUE TITLE
Can't locate Utils/PIF.pm in @INC

### ISSUE THREAD

**Issue by naiding** [agilebits/onepassword-utilities#33]
After I set up my environment and began conversion, there was an error "Can't locate Utils/PIF.pm in @INC".

I simply solved this problem by copying three folders `Utils`, `UUID` and `Converters` into `C:\myperl\perl\lib`.

Hope this could help someone.

BTW, one could use this tool `https://github.com/kspearrin/ff-password-exporter` to export passwords in firefox to `CSV` format, then to `1PIF` via this utilities.

**Comment by mikecappella** [comment]
@zhounaiding ,

The 1.10 version in Stable Bits has already addressed this.  It is available here:

https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

The Github repository is awaiting the update.
