### ISSUE TITLE
Add Prominent Caution

### ISSUE THREAD

**Issue by TechGuy2000** [AgileBits/onepassword-utilities#6]
It would be a good idea to add a prominent cautionary note that users should disable any backup services (especially cloud backup services) that monitor their desktop before running the conversion operations. Otherwise, the user could inadvertently allow their unencrypted password database to be synced or backed up to a location other than their desktop.

**Comment by mikecappella** [comment]
Hi @TechGuy2000,

This is a good idea.  However, I don't think the caution really belongs here, but instead, here: https://support.1password.com/import/, as that is the entrance route most folks will take.  By the time they get to this converter, users have often already exported the data, trying to figure out what to do.

**Comment by robyoder** [comment]
Good point, @mikecappella. I'll see if we can get it added there, but I'll also make a note here in README.md as well

**Comment by mikecappella** [comment]
OK, great.  FYI: Expect a pull request today, for v1.04.

**Comment by TechGuy2000** [comment]
Adding a caution to the 1Password import page is a good idea too! Thanks for the quick addition and for the hat tip! :-)
