### ISSUE TITLE
how to export iCloud.keychain ?

### ISSUE THREAD

**Issue by skupfer** [agilebits/onepassword-utilities#9]
thanks for this wonderful tool! so far I was able to export my login.keychain and import it into 1Password.

But how do I dump the iCloud section? I don't know why, but a lot of passwords are saved under "iCloud" instead of "Login"...

**Comment by mikecappella** [comment]
Hi Flauschie,

Please post your question here:

https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

and I'll follow-up.

**Comment by mikecappella** [comment]
FYI: this issue can be closed.  The follow-up was here:

    https://discussions.agilebits.com/discussion/comment/203120/#Comment_203120

and we resolved the issue.

**Comment by RSully** [comment]
I followed up on that thread. It doesn't look like the iCloud solution was ever posted.

**Comment by mikecappella** [comment]
Sent via PM.

Mike

**Comment by RSully** [comment]
That worked, however all of the created/modified dates get disrupted when you do that so something like Watchtower is pretty useless. Any idea if after the decrypted export it is possible to update the dates from the original iCloud keychain?

(For others looking for this his workaround is to copy items into a new blank keychain and use that new keychain to export.)

**Comment by mikecappella** [comment]
I posted in the thread.  I don’t want to have general discussions about the converters here, since this location is rather esoteric and won’t be found by most users of convert_to_1p4.

**Comment by ben181231** [comment]
Are there any reasons that you cannot post the solution here ?

**Comment by mikecappella** [comment]
Hi ben181231,

I mention one reason in the post immediately above yours.  The AgileBits GitHub repository is simply a location that AgileBits has decided to use for hosting some code.  It is not **the** forum for discussions of the converters I wrote.   It is better to have a single location for support information, and that is at the URL mentioned in my reply at the top of this chain.

I'm happy to help you, but since I help so many people, I need folks to work with me so that I can be effective.

**Comment by Nneela** [comment]
Hi there skupfer,

At first you got to know what is [icloud security code](https://www.newsfeedinternational.com/2017/11/icloud-keychain-and-security-code.html) a Password manger of apple? how its work on Apple iOS operating system.

you can read our article also search this forum for better solution.

I'm happy to help you out about this icloud issue.
